### ISSUE TITLE
provide alternative start / stop commands

### ISSUE THREAD

**Issue by alexanderadam** [ysbaddaden/prax.cr#37]
If there would be a config file with start and stop commands (plus the already provided port) it would be possible to support other projects as well.

Like docker containers, VMs etc.

I would love to see this feature although I understand that it might add more complexity as well.

A `myapp.yml` would be nice like:

```YAML
start_commands:
  - 'cd ~/myapp'
  - 'docker-compose up'
stop_commands:
  - 'docker-compose stop'
port: 3002
```
